### ISSUE TITLE
what is the CryoEm conda environment?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [BioinfoMachineLearning/cryoppp#1]
Hi

I quicky browse your git repository and find the "recipe" to build the pyem conda environment (`post_processing_scripts/convert_cs_file_to_star.py`) but not `CryoEm` referenced in `./motion_correction_files_manipulations/copy_gain_files.sh` and `./motion_correction_files_manipulations/copy_microimage_files.sh`.

I suppose that copy_gain_files.py comes from that env.

Cheers,

Tru

**Comment by Ashwin-Dhakal** [comment]
> Hi
> 
> I quicky browse your git repository and find the "recipe" to build the pyem conda environment (`post_processing_scripts/convert_cs_file_to_star.py`) but not `CryoEm` referenced in `./motion_correction_files_manipulations/copy_gain_files.sh` and `./motion_correction_files_manipulations/copy_microimage_files.sh`.
> 
> I suppose that copy_gain_files.py comes from that env.
> 
> Cheers,
> 
> Tru

Hi @truatpasteurdotfr , The Conda environment used for running these scripts is named 'CryoEm,' and all dependencies are listed in the `requirements.txt` file. However, since these Python and shell scripts were part of the data curation and handling process, you don't need to run them to access the data. Simply download the data using Option 1, 2, or 3 outlined in the repository's README.
