### ISSUE TITLE
Data inconsistency?

### ISSUE THREAD

**Issue by YuanhaoC** [BioinfoMachineLearning/cryoppp#3]
When I used this dataset recently, I noticed two micrographs contain many more false positives than true positives. When I took a closer look at these two micrographs, I thought they actually contain many true positives. Thus, I wonder whether it is mislabeling or my misinterpretation. The relevant micrographs are "Falcon_2012_06_13-01_22_31_0.mrc" and "Falcon_2012_06_13-03_24_53_0.mrc" from EMPIAR 10017. 
The left plots contain coordinates of false positive (yellow dots), and the right plots contain coordinates of true positives.
![issue1](https://github.com/BioinfoMachineLearning/cryoppp/assets/112937175/504e3ac2-491f-4e9b-9b09-b41eed3b44c5)
![issue2](https://github.com/BioinfoMachineLearning/cryoppp/assets/112937175/9fe9a29d-6593-4772-b6b9-57edcf116671)

**Comment by Ashwin-Dhakal** [comment]
Hi @YuanhaoC, 

This is happening in your case because you are not correctly interpreting the .mrc file. I understand the complexity involved, especially when loading and visualizing the micrograph in .mrc format. We adopted a distinct approach while reading micrographs to ensure compatibility with CryoSPARC.

Please use these steps to load the micrographs in MRC format: 

```
import mrcfile
micrograph_path = 'path/to/mrc/file'
image = mrcfile.read(micrograph_path)
image = image.T
image = np.rot90(image)
image = transform(image)
```
then, plot the image and the coordinates from the corresponding CSV file. 

If you find this complicated, you can use CryoPPP_Lite, (http://calla.rnet.missouri.edu/cryoppp_lite) where all the micrographs are already converted to jpg files for ease. Moreover, it is lightweight, allowing you to effortlessly plot circles on the micrograph image without any complications.  

Hope this helps.

**Comment by YuanhaoC** [comment]
I can try this method soon, but I don't see the difference between this method and mine. So let me describe the issue in a clearer way.

Whatever the correct way to interpret a .mrc file is, I have managed to match the micrographs and coordinates, except these two. If a method works on other data but fails on two cases, maybe these two cases are special? Or the method is limited?

So I guess maybe the labels of these two micrographs are mismatched.

**Comment by YuanhaoC** [comment]
I can try this method soon, but I don't see the difference between this method and mine. So let me describe the issue in a clearer way.

Whatever the correct way to interpret a .mrc file is, I have managed to match the micrographs and coordinates, except these two. If a method works on other data but fails on two cases, maybe these two cases are special? Or the method is limited?

So I guess maybe the labels of these two micrographs are mismatched.

**Comment by KiSchnelle** [comment]
Do i have to do any transform if i take the mrc from the micrograph folder and the particles_selected.star file from the ground truth? Like are just the CSV file coordinates different or also the star files ones?

**Comment by YuanhaoC** [comment]
> Do i have to do any transform if i take the mrc from the micrograph folder and the particles_selected.star file from the ground truth? Like are just the CSV file coordinates different or also the star files ones?

If I remember right, .star files are fine

**Comment by KiSchnelle** [comment]
sadly not apperently, thanks though:) trying to figure it out. Really like the idea of this dataset but the format is really not clear labeled, sometimes there are just micrograph folder, sometimes motion corrected, then there is one dataset with subdatasets, that really doesnt make preparation easily scriptable :D

**Comment by Ashwin-Dhakal** [comment]
> Do i have to do any transform if i take the mrc from the micrograph folder and the particles_selected.star file from the ground truth? Like are just the CSV file coordinates different or also the star files ones?

@KiSchnelle , Both the .csv and .star files contain the same x and y coordinates of the micrographs. The .star files are provided because they are easily imported into Cryo-EM processing software such as RELION and CryoSPARC. Meanwhile, the .csv files are useful for data manipulation from a machine learning perspective, such as creating masks or labels for ML applications.

**Comment by Ashwin-Dhakal** [comment]
> sadly not apperently, thanks though:) trying to figure it out. Really like the idea of this dataset but the format is really not clear labeled, sometimes there are just micrograph folder, sometimes motion corrected, then there is one dataset with subdatasets, that really doesnt make preparation easily scriptable :D

If an entry has a ‘gain’ folder, it includes both raw non-motion-corrected micrographs and their motion-corrected counterparts created by us. Users are supposed to use the motion corrected micrographs as input for machine learning tasks.

Hope this helps to understand the data records.
